AWSTemplateFormatVersion: '2010-09-09'
Description: Runs a service on a docker image by spinning a single ec2 instance.

Parameters:
  InputDomainName:
    Type: String
    Description: Origin domain name that get's redirected to the cloudfront distribution. For example, 'www.domain-name.com'. Must match the ACM certificate.
  TargetDomainName:
    Type: String
    Description: Cloudfront redirects in http to this
  UsEast1CertificateArn:
    Type: String
    Description: ARN of the ACM certificate for the hosted zone.Must be located in us-east-1 region
  HostedZoneId:
    Type: String
    Description: The ID of the Route53 hosted zone to create the CNAME record in.

Resources:
  CloudFrontOriginRequestPolicy:
    Type: AWS::CloudFront::OriginRequestPolicy
    Properties:
      OriginRequestPolicyConfig:
        Name: CloudFrontOriginRequestPolicy
        CookiesConfig:
          CookieBehavior: all
        HeadersConfig:
          HeaderBehavior: allViewerAndWhitelistCloudFront
          Headers:
            - CloudFront-Forwarded-Proto
        QueryStringsConfig:
          QueryStringBehavior: all
  CloudFrontCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: CloudFrontCachePolicy
        DefaultTTL: 3600
        MaxTTL: 86400
        MinTTL: 0
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          EnableAcceptEncodingBrotli: true
          EnableAcceptEncodingGzip: true
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: all
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - Id: EC2Origin
            DomainName: !Ref TargetDomainName
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
              HTTPPort: 80
        DefaultCacheBehavior:
          TargetOriginId: EC2Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - POST
            - PATCH
            - DELETE
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachePolicyId: !Ref CloudFrontCachePolicy
          OriginRequestPolicyId: !Ref CloudFrontOriginRequestPolicy
        ViewerCertificate:
          AcmCertificateArn: !Ref UsEast1CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Aliases:
          - !Ref InputDomainName
        HttpVersion: http2
        PriceClass: PriceClass_100
  CNAMERecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref InputDomainName
      Type: CNAME
      TTL: '300'
      ResourceRecords:
        - !GetAtt CloudFrontDistribution.DomainName

Outputs:
  CloudFrontDomainName:
    Value: !GetAtt CloudFrontDistribution.DomainName