AWSTemplateFormatVersion: '2010-09-09'
Description: Runs a service on a docker image by spinning a single ec2 instance.

Parameters:
  DockerImage:
    Type: String
    Description: The URI of the image to use (from AWS ECR or a public repository).
  VpcId:
    Type: String
    Description: The VPC ID to create the instance in
  SubnetId:
    Type: String
    Description: The ID of the VPC subnet to create the instance in

  InstanceType:
    Type: String
    Description: EC2 instance Type
    Default: t3.micro
  DiskSpaceGib:
    Type: Number
    Description: Disk space in gB
    Default: '20'
  EnvironmentVariables:
    Type: String
    Default: ''
    Description: 'The environment variables to pass to the docker image. Example: !Sub "-e AWS_DEFAULT_REGION=${AWS::Region} -e AWS_STACK_NAME=${AWS::StackName}"'
  RolePolicyArns:
    Type: String
    Description: Comma-separated list of managed policy ARNs to attach to the EC2 role. Or an empty string for default rights.
    Default: ''
  SSHKeyName:
    Type: String
    Description: The name of an existing EC2 KeyPair to enable SSH access to the instances (optional). Leave empty to not use a key pair (ssh port will be closed).
    Default: ''
  LogGroupName:
    Type: String
    Default: "/ec2/service"

Conditions:
  HasSSHKeyName: !Not [!Equals ['', !Ref SSHKeyName]]
  NotHasPolicy: !Equals ['', !Ref RolePolicyArns]

Resources:
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for runners
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - !If
          - HasSSHKeyName
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: 0.0.0.0/0
          - !Ref AWS::NoValue
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: '-1'
          CidrIp: 0.0.0.0/0
  EC2LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Ref LogGroupName
      RetentionInDays: 30
  DefaultPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub ${AWS::StackName}-DefaultPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - ecr:GetAuthorizationToken
              - ecr:BatchCheckLayerAvailability
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
            Resource: "*"
  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns: !If
        - NotHasPolicy
        - - !Ref DefaultPolicy
          - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - !Split
          - ','
          - !Join
            - ','
            - - !Ref DefaultPolicy
              - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
              - !Ref RolePolicyArns
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2InstanceRole
  EC2Instance:
    Type: AWS::EC2::Instance
    DependsOn: EC2LogGroup
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Sub '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}'
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: !Ref DiskSpaceGib
            VolumeType: gp3
            DeleteOnTermination: true
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      IamInstanceProfile: !Ref EC2InstanceProfile
      KeyName: !If
        - HasSSHKeyName
        - !Ref SSHKeyName
        - !Ref AWS::NoValue
      MetadataOptions:
        HttpTokens: required
        HttpEndpoint: enabled
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -x
          dnf update -y
          # Install CloudWatch Agent
          dnf install -y amazon-cloudwatch-agent
          # Install and start Docker
          dnf install -y docker
          systemctl enable docker
          systemctl start docker
          usermod -a -G docker ec2-user
          # Install and start SSM Agent
          dnf install -y amazon-ssm-agent
          systemctl enable amazon-ssm-agent
          systemctl start amazon-ssm-agent
          # Pull and run Docker container
          aws ecr get-login-password --region ${AWS::Region} | docker login --username AWS --password-stdin ${DockerImage}
          docker pull ${DockerImage}
          echo ${LogGroupName}
          docker run -d --network host -e AWS_DEFAULT_REGION=${AWS::Region} ${EnvironmentVariables} --log-driver=awslogs --log-opt awslogs-region=${AWS::Region} --log-opt awslogs-group=${LogGroupName} --log-opt awslogs-stream=docker-logs-$(date +%s) ${DockerImage}
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-Instance

Outputs:
  EC2InstanceId:
    Value: !Ref EC2Instance
  EC2PrivateIP:
    Value: !GetAtt EC2Instance.PrivateIp
  EC2PublicIP:
    Value: !GetAtt EC2Instance.PublicIp
  EC2PublicDnsName:
    Value: !GetAtt EC2Instance.PublicDnsName